version: '3.1'

services:
  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://datastore:27017"
    links:
      - datastore
    depends_on:
      - datastore

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://datastore:27017"
    links:
      - datastore
    depends_on:
      - datastore

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "database"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "micro"
    links:
      - database
    depends_on:
      - database
      
  datastore:
    image: mongo
    ports:
      - 27017:27017
  
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "micro"
      POSTGRES_DB: "postgres"

  vessel-cli:
    build: ./vessel-cli

  consignment-cli:
    build: ./consignment-cli

  user-cli:
    build: ./user-cli