version: '3.1'

services:
  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://datastore:27017"
    links:
      - datastore
    depends_on:
      - datastore

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://datastore:27017"
    links:
      - datastore
    depends_on:
      - datastore

  datastore:
    image: mongo
    ports:
      - 27017:27017

  vessel-cli:
    build: ./vessel-cli

  consignment-cli:
    build: ./consignment-cli